### ISSUE TITLE
Missing importlib library

### ISSUE THREAD

**Issue by cavelandiah** [Bierinformatik/MIRfix#3]
https://github.com/Bierinformatik/MIRfix/blob/d7d5138811a66dd17dca9450cfbb439a6f185578/scripts/MIRfix.py#L28

In comparison to other versions, there is complaining about the missing line:
`import importlib` 
at now, there are no references for this library, generating the attached error
[error.txt](https://github.com/Bierinformatik/MIRfix/files/3451342/error.txt)

**Comment by jfallmann** [comment]
@cavelandiah This should be fixed
