### ISSUE TITLE
clustalw to clustalw2?

### ISSUE THREAD

**Issue by cavelandiah** [Bierinformatik/MIRfix#5]
Maybe is better in terms of speed, as referred on [this reference](https://academic.oup.com/bioinformatics/article/23/21/2947/371686): 

>The Clustal W and Clustal X multiple sequence alignment programs have been completely rewritten in C++.
>Two new options have been included in Clustal W 2.0, to allow faster alignment of very large data sets and to increase alignment accuracy. 
> We have reimplemented a very efficient algorithm for UPGMA which can be called by using the command line option ‘-clustering=UPGMA’. It is marginally less accurate on the Balibase benchmark, but on large alignments (e.g. 10 000 globin sequences) this is offset by the savings in processing time (2 h versus 12 h).

https://github.com/Bierinformatik/MIRfix/blob/d7d5138811a66dd17dca9450cfbb439a6f185578/scripts/MIRfix.py#L3495

**Comment by jfallmann** [comment]
This was already implemented and simply forgotten when migrating from subprocess to biopython, thanks for the catch, might also help with #7
