### ISSUE TITLE
clustalw cut the names

### ISSUE THREAD

**Issue by cavelandiah** [Bierinformatik/MIRfix#7]
In this case, I detected that some examples when the header id is too long clustalw without generates an error or warning cuts the id name, see in the attached image.
![errorClustalWnames](https://user-images.githubusercontent.com/15683571/62465267-c5021d80-b78e-11e9-8e87-c4babd0a0345.png)

https://github.com/Bierinformatik/MIRfix/blob/d7d5138811a66dd17dca9450cfbb439a6f185578/scripts/MIRfix.py#L2554

**Comment by jfallmann** [comment]
@cavelandiah This is true and known behaviour for ClustalW but I do not have a workaround at hand other than patching clustalw.h and changing the #define MAXNAMES	> 10 
see ClustalW help:
```5. The clustal sequence alignment file format has been changed to allow
sequence names longer than 10 characters. The maximum length allowed is set in
clustalw.h by the statement:
#define MAXNAMES	10

For the fasta format, the name is taken as the first string after the '>'
character, stopping at the first white space. (Previously, the first 10
characters were taken, replacing blanks by underscores).```
